# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cf13aed00a78b7d30e7ef6b3e61d5f2d4fffdb39bd30c54f12c89f12204b5310fee7171b5b2881514dbdcf8057c20df82f10a813ceb2432f16e13afbfa6bfc6e

test:
  secret_key_base: 9587e290d00d6b02d37a548ee307710b209cfb36102c4f89ba14537e69b5f72286dce0130d0fdfdcee99fad33c8470de6c781fac628b07da9f20d4f50e7d0507

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
